### ISSUE TITLE
Does not work with backpack crud 3.3.0

### ISSUE THREAD

**Issue by imcodingideas** [novius/laravel-backpack-crud-extended#28]
I know this was a workaround to get this feature sooner than they merged to master. Do you plan on supporting backpack crud 3.3.0

“novius/laravel-backpack-crud-extended”: “^0.2.6"

Your requirements could not be resolved to an installable set of packages.

 Problem 1

    - Installation request for novius/laravel-backpack-crud-extended ^0.2.6 -> satisfiable by novius/laravel-backpack-crud-extended[0.2.6].

    - novius/laravel-backpack-crud-extended 0.2.6 requires backpack/crud ~3.2.15 -> satisfiable by backpack/crud[3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.20, 3.2.21, 3.2.22, 3.2.23, 3.2.24, 3.2.25, 3.2.26, 3.2.27, 3.2.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by jguyomard** [comment]
Hello,

Yes, supporting Backpack\Crud 3.3 is planned this month.

I will keep you informed,

**Comment by jguyomard** [comment]
Hello,

`novius/laravel-backpack-crud-extended 0.3.*` is published since last week. We have tested it in some projects, it seems to work well.

Have a good day,
