### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by mambax7** [novius/laravel-backpack-crud-extended#3]
You might have problems with the licence. I might be wrong, but I don't think that if you extend Open Source software, you're allowed to switch the licence to something different. 
They have YUMMY licence:
https://github.com/Laravel-Backpack/CRUD/blob/master/LICENSE.md
You switched to: GNU Affero General Public License v3

**Comment by jguyomard** [comment]
Hello,

You may be right, i dont know. I always use the AGPL-3 license without thinking.

I thought Backpack\CRUD was under "MIT" licence (as shown [here](https://github.com/Laravel-Backpack/CRUD/blob/4551ac1f1ba9060b959e1592c116bbd75e3f7545/composer.json)) but actually it seems to have changed. You're right about this.

We don't want to make money with this package. But if someones uses it in a commercial projet, and therefore uses Backpack\CRUD in a commercial project, he will have to buy a backpack license. 
Maybe we have to add a note about this. For instance:

> # Licence
> 
> This package is under GNU Affero General Public License v3 or (at your option) any later version.
> 
> However, this package requires Backpack\CRUD, which is under YUMMY license: if you use it in a commercial project, you have to [buy a backpack license](https://backpackforlaravel.com/pricing).

What do you think about this @tabacitu? You can contact me by email if you prefer (you can find it into `composer.json` file).

**Comment by mambax7** [comment]
Normally, when you "extend" somebody's source code, you're creating "derivative" work, and that works should keep the same license. 
If you're calling a function in a library, than you can use whatever license you want for "your" program. 

In your case, you do "extend", so you should not change the license.

Of course, there is a different question, if they did it properly by using YUMMY license instead of the original MIT License, but I didn't look in their code so I don't know if it was a "derivative" work or not.

**Comment by tabacitu** [comment]
Hi guys,

@jguyomard  thanks for letting me know. I don't see a problem with this, but I'm no legal expert. I see:
- you required backpack\crud, which is fine
- you mentioned your work is free for commercial use
- you mentioned a dependency is NOT free for commercial use and provided a link to purchase

I think you've done all you need to do :-) Maybe mention a mixed license in your README, at the bottom, so it's crystal-clear? That's it.

Cheers!

PS. Great job with this, eager to have some of these features in the main package soon :-)

**Comment by jguyomard** [comment]
Hi @tabacitu,

Thank you for your reply.
I've update our "licence" note in our README, so it's crystal-clear now :)

Cheers!
