### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by cerelli** [novius/laravel-backpack-crud-extended#36]
Hello and congratulations for the work done. 
I wanted to know how to configure laravel to be able to make the changes I need on the fork and then request a pull.
Thank you.

Marco.

**Comment by jguyomard** [comment]
Hello,

You just have to clone your fork in `vendor/novius/laravel-backpack-crud-extended`. 
If your `preferred-install` config is "source" in your `composer.json`, you can also jump to `vendor/novius/laravel-backpack-crud-extended`, add your fork url as remote and checkout to your branch.
