### ISSUE TITLE
installation with backpack 3.4 problem

### ISSUE THREAD

**Issue by mikiman2028** [novius/laravel-backpack-crud-extended#39]
"Your requirements could not be resolved to an installable set of packages"
 - novius/laravel-backpack-crud-extended 0.2.8 requires backpack/crud ~3.2.15 -> satisfiable by backpack/crud[3.2.x-dev]... 
is there any way to fix this?

**Comment by shaoshiva** [comment]
Hello,

The latest version of `backpack/crud` we support is `3.3` and we have not yet planned to release a version compatible with `3.4` (maybe in the coming weeks).

In the meantime, you can use the `0.4` branch which requirements are compatible with backpack `3.4`. To do this you have to change the version of `novius/laravel-backpack-crud-extended` to `0.4.x-dev` in your `composer.json`.

Let me know if it works.

**Comment by mikiman2028** [comment]
it works with 0.4.x-dev. Thank you!!

**Comment by shaoshiva** [comment]
You're welcome !

**Comment by iMokhles** [comment]
installed dev branch for latest version ( but boxes don't work ) is that normal ?

**Comment by iMokhles** [comment]
it worked now ( i hadn't publish views well but now it works )
thanks for those extended features ( saved me a lot of hours of work )
and it serve my needs completely ( it's an open source project )
will let you know when i open source it completely.

![capture d ecran 2018-04-13 a 03 19 46](https://user-images.githubusercontent.com/1247248/38712043-95743da8-3ec9-11e8-9655-8ea88119c84b.png)

**Comment by shaoshiva** [comment]
Thanks for your feedback !
